In [ ]:
k = 3

query = [5, 7, 8, 10, 12, "class"]
query_title = ["玩命關頭"]

db = [[2, 8, 8, 5, 6, "動作片"],
      [5, 6, 9, 2, 5, "動作片"],
      [8, 2, 0, 0, 10, "家庭片"],
      [5, 8, 8, 8, 3, "動作片"]]


In [ ]:
import math

def knn(db, query, k):
    dis_seq = []
    cla_seq = []

    for r in db:
        dis = 0
        for i in range(len(query) - 1):
            dis = dis + (query[i] - r[i])**2
        dis = math.sqrt(dis)

        dis_seq.append(dis)
        cla_seq.append(r[-1])

    knn_dis = []
    knn_cla = []

    for i in range(k):
        min_v1 = min(dis_seq)
        min_vi = dis_seq.index(min_v1)

        knn_dis.append(dis_seq.pop(min_vi))
        knn_cla.append(cla_seq.pop(min_vi))

    return knn_cla, knn_dis


(['動作片', '動作片', '動作片'], [8.426149773176359, 9.273618495495704, 10.723805294763608])


In [ ]:
def knn_classify(knn_cla):
    class_set = set(knn_cla)
    print(class_set)

    predicted = ""
    vote_num = 0

    for e in class_set:
        if knn_cla.count(e) > vote_num:
            vote_num = knn_cla.count(e)
            predicted = e

    return predicted

print(knn_classify(knn(db, query, k)[0]))


{'動作片'}
動作片


In [ ]:
knn_ds = knn(db, query, k)
predicted = knn_classify(knn_ds[0])

print("[{}] 被分類為 {}".format(query_title, predicted))

for j in range(k):
    print("鄰居 {} 的類別為 {}，與 query 距離為 {}".format(j, knn_ds[0][j], knn_ds[1][j]))


{'動作片'}
[['玩命關頭']] 被分類為 動作片
鄰居 0 的類別為 動作片，與 query 距離為 8.426149773176359
鄰居 1 的類別為 動作片，與 query 距離為 9.273618495495704
鄰居 2 的類別為 動作片，與 query 距離為 10.723805294763608


In [28]:
import numpy as np

y_true = ['A', 'B', 'C', 'B', 'A', 'C', 'B', 'A', 'C']
y_pred = ['A', 'C', 'C', 'B', 'A', 'C', 'A', 'A', 'B']

def confusion_matrix(y_true, y_pred):
    labels = sorted(set(y_true) | set(y_pred))
    n_labels = len(labels)
    matrix = np.zeros((n_labels, n_labels), dtype = int)

    for true, pred in zip(y_true, y_pred):
        print(true, pred)
        matrix[labels.index(true)][labels.index(pred)] += 1

    return matrix, labels


In [29]:
matrix, labels = confusion_matrix(y_true, y_pred)
print(labels)
print(matrix)


A A
B C
C C
B B
A A
C C
B A
A A
C B
['A', 'B', 'C']
[[3 0 0]
 [1 1 1]
 [0 1 2]]


In [39]:
def calculate_metrics(confusion_matrix):
    metrics = []
    n = len(confusion_matrix)
    print(n)

    for i in range(n):
        precision = confusion_matrix[i][i] / sum(confusion_matrix[i])
        print(precision)
        recall = confusion_matrix[i][i] / sum(confusion_matrix[:, i])
        print(recall)
        f_measure = (2 * precision * recall) / (precision + recall)
        print(f_measure)

        metrics.append({
            'class': i,
            'precision': precision,
            'recall': recall,
            'f_measure': f_measure
        })

    return metrics

In [41]:
metrics = calculate_metrics(matrix)

for m in metrics:
    print('Class: ', m['class'])
    print('Precision: ', m['precision'])
    print('Recall: ', m['recall'])
    print('F-measure: ', m['f_measure'])
    print("==============")


3
1.0
0.75
0.8571428571428571
0.3333333333333333
0.5
0.4
0.6666666666666666
0.6666666666666666
0.6666666666666666
Class:  0
Precision:  1.0
Recall:  0.75
F-measure:  0.8571428571428571
Class:  1
Precision:  0.3333333333333333
Recall:  0.5
F-measure:  0.4
Class:  2
Precision:  0.6666666666666666
Recall:  0.6666666666666666
F-measure:  0.6666666666666666
